<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
    ['currency_code' => 'AED', 'currency_name' => 'Emirati Dirham'],
    ['currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani'],
    ['currency_code' => 'ALL', 'currency_name' => 'Albanian lek'],
    ['currency_code' => 'AMD', 'currency_name' => 'Armenian dram'],
    ['currency_code' => 'ANG', 'currency_name' => 'Dutch Guilder'],
    ['currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza'],
    ['currency_code' => 'ARS', 'currency_name' => 'Argentine peso'],
    ['currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
    ['currency_code' => 'AWG', 'currency_name' => 'Arubin florin'],
    ['currency_code' => 'AZN', 'currency_name' => 'Azerbaijani manat'],
    ['currency_code' => 'BAM', 'currency_name' => 'Bosnian Convertible Marka'],
    ['currency_code' => 'BBD', 'currency_name' => 'Barbadian dollar'],
    ['currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka'],
    ['currency_code' => 'BGN', 'currency_name' => 'Bulgarian lev'],
    ['currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar'],
    ['currency_code' => 'BIF', 'currency_name' => 'Burundian Franc'],
    ['currency_code' => 'BMD', 'currency_name' => 'Bermudian dollar'],
    ['currency_code' => 'BND', 'currency_name' => 'Bruneian Dollar'],
    ['currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano'],
    ['currency_code' => 'BRL', 'currency_name' => 'Brazilian real'],
    ['currency_code' => 'BSD', 'currency_name' => 'Bahamian dollar'],
    ['currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum'],
    ['currency_code' => 'BWP', 'currency_name' => 'Botswana Pula'],
    ['currency_code' => 'BYR', 'currency_name' => 'Belarusian ruble'],
    ['currency_code' => 'BZD', 'currency_name' => 'Belize dollar'],
    ['currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar'],
    ['currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
    ['currency_code' => 'CLP', 'currency_name' => 'Chilean Peso'],
    ['currency_code' => 'CNY', 'currency_name' => 'Yuan or Chinese Renminbi'],
    ['currency_code' => 'COP', 'currency_name' => 'Colombian peso'],
    ['currency_code' => 'CRC', 'currency_name' => 'Costa Rican colón'],
    ['currency_code' => 'CUC', 'currency_name' => 'Cuban convertible peso'],
    ['currency_code' => 'CUP', 'currency_name' => 'Cuban peso'],
    ['currency_code' => 'CVE', 'currency_name' => 'Cape Verdean Escudo'],
    ['currency_code' => 'CZK', 'currency_name' => 'Czech koruna'],
    ['currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc'],
    ['currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
    ['currency_code' => 'DOP', 'currency_name' => 'Dominican peso'],
    ['currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar'],
    ['currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound'],
    ['currency_code' => 'ERN', 'currency_name' => 'Eritrean nakfa'],
    ['currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr'],
    ['currency_code' => 'EUR', 'currency_name' => 'Euro'],
    ['currency_code' => 'FJD', 'currency_name' => 'Fijian dollar'],
    ['currency_code' => 'FKP', 'currency_name' => 'Falkland Island Pound'],
    ['currency_code' => 'GBP', 'currency_name' => 'British Pound'],
    ['currency_code' => 'GEL', 'currency_name' => 'Georgian lari'],
    ['currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi'],
    ['currency_code' => 'GIP', 'currency_name' => 'Gibraltar pound'],
    ['currency_code' => 'GMD', 'currency_name' => 'Gambian dalasi'],
    ['currency_code' => 'GNF', 'currency_name' => 'Guinean Franc'],
    ['currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal'],
    ['currency_code' => 'GYD', 'currency_name' => 'Guyanese dollar'],
    ['currency_code' => 'HKD', 'currency_name' => 'Hong Kong dollar'],
    ['currency_code' => 'HNL', 'currency_name' => 'Honduran lempira'],
    ['currency_code' => 'HRK', 'currency_name' => 'Croatian kuna'],
    ['currency_code' => 'HTG', 'currency_name' => 'Haitian gourde'],
    ['currency_code' => 'HUF', 'currency_name' => 'Hungarian forint'],
    ['currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah'],
    ['currency_code' => 'ILS', 'currency_name' => 'Israeli Shekel'],
    ['currency_code' => 'INR', 'currency_name' => 'Indian Rupee'],
    ['currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar'],
    ['currency_code' => 'IRR', 'currency_name' => 'Iranian Rial'],
    ['currency_code' => 'ISK', 'currency_name' => 'Icelandic Krona'],
    ['currency_code' => 'JMD', 'currency_name' => 'Jamaican dollar'],
    ['currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar'],
    ['currency_code' => 'JPY', 'currency_name' => 'Japanese yen'],
    ['currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling'],
    ['currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani som'],
    ['currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel'],
    ['currency_code' => 'KMF', 'currency_name' => 'Comoran Franc'],
    ['currency_code' => 'KPW', 'currency_name' => 'North Korean won'],
    ['currency_code' => 'KRW', 'currency_name' => 'South Korean won'],
    ['currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar'],
    ['currency_code' => 'KYD', 'currency_name' => 'Caymanian Dollar'],
    ['currency_code' => 'KZT', 'currency_name' => 'Kazakhstani tenge'],
    ['currency_code' => 'LAK', 'currency_name' => 'Lao or Laotian Kip'],
    ['currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound'],
    ['currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee'],
    ['currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar'],
    ['currency_code' => 'LSL', 'currency_name' => 'Lesotho loti'],
    ['currency_code' => 'LTL', 'currency_name' => 'Lithuanian litas'],
    ['currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar'],
    ['currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham'],
    ['currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu'],
    ['currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary'],
    ['currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar'],
    ['currency_code' => 'MMK', 'currency_name' => 'Burmese Kyat'],
    ['currency_code' => 'MNT', 'currency_name' => 'Mongolian Tughrik'],
    ['currency_code' => 'MOP', 'currency_name' => 'Macau Pataca'],
    ['currency_code' => 'MRO', 'currency_name' => 'Mauritanian Ouguiya'],
    ['currency_code' => 'MUR', 'currency_name' => 'Mauritian rupee'],
    ['currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa'],
    ['currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha'],
    ['currency_code' => 'MXN', 'currency_name' => 'Mexico Peso'],
    ['currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit'],
    ['currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical'],
    ['currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar'],
    ['currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira'],
    ['currency_code' => 'NIO', 'currency_name' => 'Nicaraguan córdoba'],
    ['currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
    ['currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee'],
    ['currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar'],
    ['currency_code' => 'OMR', 'currency_name' => 'Omani Rial'],
    ['currency_code' => 'PAB', 'currency_name' => 'Balboa panamérn'],
    ['currency_code' => 'PEN', 'currency_name' => 'Peruvian nuevo sol'],
    ['currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina'],
    ['currency_code' => 'PHP', 'currency_name' => 'Philippine Peso'],
    ['currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee'],
    ['currency_code' => 'PLN', 'currency_name' => 'Polish złoty'],
    ['currency_code' => 'PYG', 'currency_name' => 'Paraguayan guarani'],
    ['currency_code' => 'QAR', 'currency_name' => 'Qatari Riyal'],
    ['currency_code' => 'RON', 'currency_name' => 'Romanian leu'],
    ['currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar'],
    ['currency_code' => 'RUB', 'currency_name' => 'Russian Rouble'],
    ['currency_code' => 'RWF', 'currency_name' => 'Rwandan franc'],
    ['currency_code' => 'SAR', 'currency_name' => 'Saudi Arabian Riyal'],
    ['currency_code' => 'SBD', 'currency_name' => 'Solomon Islander Dollar'],
    ['currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee'],
    ['currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound'],
    ['currency_code' => 'SEK', 'currency_name' => 'Swedish krona'],
    ['currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar'],
    ['currency_code' => 'SLL', 'currency_name' => 'Sierra Leonean Leone'],
    ['currency_code' => 'SOS', 'currency_name' => 'Somali Shilling'],
    ['currency_code' => 'SRD', 'currency_name' => 'Surinamese dollar'],
    ['currency_code' => 'SSP', 'currency_name' => 'South Sudanese pound'],
    ['currency_code' => 'SYP', 'currency_name' => 'Syrian Pound'],
    ['currency_code' => 'SZL', 'currency_name' => 'Swazi Lilangeni'],
    ['currency_code' => 'THB', 'currency_name' => 'Thai Baht'],
    ['currency_code' => 'TJS', 'currency_name' => 'Tajikistani somoni'],
    ['currency_code' => 'TMT', 'currency_name' => 'Turkmenistan manat'],
    ['currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar'],
    ['currency_code' => 'TOP', 'currency_name' => 'Tongan Pa\'anga'],
    ['currency_code' => 'TRY', 'currency_name' => 'Turkish Lira'],
    ['currency_code' => 'TTD', 'currency_name' => 'Trinidadian dollar'],
    ['currency_code' => 'TWD', 'currency_name' => 'Taiwan New Dollar'],
    ['currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling'],
    ['currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia'],
    ['currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling'],
    ['currency_code' => 'USD', 'currency_name' => 'US Dollar'],
    ['currency_code' => 'UYU', 'currency_name' => 'Uruguayan peso'],
    ['currency_code' => 'UZS', 'currency_name' => 'Uzbekistani som'],
    ['currency_code' => 'VEF', 'currency_name' => 'Venezuelan bolivar'],
    ['currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong'],
    ['currency_code' => 'VUV', 'currency_name' => 'Ni-Vanuatu Vatu'],
    ['currency_code' => 'WST', 'currency_name' => 'Samoan Tālā'],
    ['currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
    ['currency_code' => 'XOF', 'currency_name' => 'CFA Franc'],
    ['currency_code' => 'XPF', 'currency_name' => 'CFP Franc'],
    ['currency_code' => 'YER', 'currency_name' => 'Yemeni Rial'],
    ['currency_code' => 'ZAR', 'currency_name' => 'South African Rand'],
    ['currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha'],
    ['currency_code' => 'ZWD', 'currency_name' => 'Zimbabwean Dollar']
];


        DB::table('currencies')->insert($currencies);
    }
}
